### PR TITLE
Remove duplicate meta file

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Remove duplicate `.meta` file from the root folder as the meta files for OS is under `plugins/.meta` and OSD is under `dashboards-plugins/.meta `

Fix few broken links for the `linkchecker` to pass.

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/3616 and https://github.com/opensearch-project/.github/issues/167

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Comment by dblock** [comment]
The intent of the top-level meta was to have a sum of all plugins, especially that there used to be duplicates where an OpenSearch plugin and a Dashboards plugin were in the same repo.

**Comment by gaiksaya** [comment]
Yeah even for compatibility check which is using plugins/.meta file, `oci-object-storage` is one of the component. Any way to filter out what projects are actually active / part of release and which are upcoming?

**Comment by prudhvigodithi** [comment]
Ya this `.meta` list is not the right way to move forward, we need to create a release issue in OpenSearch and OpenSearch Dashboards repo as well, whereas in `.meta` the list only confines to the plugins, a release manager might miss to create a release issue in core repos.

**Comment by gaiksaya** [comment]
> Ya this `.meta` list is not the right way to move forward, we need to create a release issue in OpenSearch and OpenSearch Dashboards repo as well, whereas in `.meta` the list only confines to the plugins, a release manager might miss to create a release issue in core repos.

@prudhvigodithi @dblock But manifest might not be the source of truth as plugins are added incrementally. Does it make sense to have 1.x, 2,x and 3.x default manifests with all plugins in the list?
Many times we remove components from the manifest to unblock a build (for now), not ready, etc. so might be misleading at the start of the release cycle.

**Comment by dblock** [comment]
What do you think about a solution where the list of plugins always exists in the build manifest, https://github.com/opensearch-project/opensearch-build/issues/3707?

**Comment by gaiksaya** [comment]
> What do you think about a solution where the list of plugins always exists in the build manifest, [opensearch-project/opensearch-build#3707](https://github.com/opensearch-project/opensearch-build/issues/3707)?

This also makes sense. Would it be too much confusing? Placeholder / non-placeholder?

**Comment by dblock** [comment]
> > What do you think about a solution where the list of plugins always exists in the build manifest, [opensearch-project/opensearch-build#3707](https://github.com/opensearch-project/opensearch-build/issues/3707)?
> 
> This also makes sense. Would it be too much confusing? Placeholder / non-placeholder?

We can discuss it in that proposal.

**Pull request merged**
