### PR TITLE
Added ml-commons.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description
Added ml-commons.
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by saratvemulapalli — APPROVED** [review]

**Review by ohltyler — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
@dblock , thanks a lot. Didn't know we should add new plugin to `opensearch-plugins`.

**Comment by dblock** [comment]
@ylwu-amzn We use meta to operate on sets of repos, not sure where/how we should document this.

**Comment by ylwu-amzn** [comment]
> @ylwu-amzn We use meta to operate on sets of repos, not sure where/how we should document this.

Not sure if we have an official doc for plugin development. If we have, we should add to there. If no and not so necessary to add it, I think it's also ok to add to OpenSearch contributing doc https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md

**Comment by dblock** [comment]
> > @ylwu-amzn We use meta to operate on sets of repos, not sure where/how we should document this.
> 
> Not sure if we have an official doc for plugin development. If we have, we should add to there. If no and not so necessary to add a new doc for plugin development, I think it's also ok to add to OpenSearch contributing doc https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md

This project is a good repository for anything plugin development, including a guide. See https://github.com/opensearch-project/opensearch-plugins#opensearch-plugins for a skeleton of plugin-related topics.

**Pull request merged**
