### PR TITLE
Document bwc test matrix strategy

### PR DESCRIPTION
**Pull request by peternied**
Signed-off-by: Peter Nied <petern@amazon.com>

### Description
Documents the bwc test matrix that should be tested against as new version numbers are generated.

### Issues Resolved
* Closes https://github.com/opensearch-project/OpenSearch/issues/3440

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@opensearch-project/plugins Could I get a review please?

**Review by saratvemulapalli — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]
LGTM!

**Comment by peternied** [comment]
@opensearch-project/plugins Could I get another approval?

**Comment by saratvemulapalli** [comment]
@ohltyler could you help review this?

**Review by ohltyler — APPROVED** [review]
LGTM!

**Pull request merged**
