### PR TITLE
Adding documentation for auto create issue workflow

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
Adding documentation for auto creating issues in `documentation-website` repo when a label `needs-documentation` is added on a PR.
 
### Issues Resolved
Related https://github.com/opensearch-project/.github/issues/57
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
At the very least this and BACKPORTs should be linked from README, but how do you feel about combining these workflows into a single file called WORKFLOWS or adding them to BUILDING.md?

**Comment by VachaShah** [comment]
> At the very least this and BACKPORTs should be linked from README, but how do you feel about combining these workflows into a single file called WORKFLOWS or adding them to BUILDING.md?

Adding them to a common md file sounds good! `BUILDING.md` looks like it serves a different purpose, adding them to `WORKFLOWS` since there are already 3 workflows - backport, labels, documentation issues.

**Review by dblock — APPROVED** [review]
👏

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
Lately we have been pushing in developer documentation here which has wider scope (i.e core, plugins, dashboards, clients etc)
May be the right time to think about switching over to `opesearch-project/.github` for future updates? 
@dblock @VachaShah

**Comment by VachaShah** [comment]
> Lately we have been pushing in developer documentation here which has wider scope (i.e core, plugins, dashboards, clients etc) May be the right time to think about switching over to `opesearch-project/.github` for future updates? @dblock @VachaShah

True, `.github` would be a good place to add all of this common documentation.

**Comment by dblock** [comment]
The .github repo is a _template_ repo for the organization. The repo for documentation that applies to all projects is https://github.com/opensearch-project/project-meta. Some stuff should actually move out of .github.

**Pull request merged**
