### PR TITLE
Documenting usage of overriding Default Distribution Download URL with custom URL by setting external property customDistributionUrl

### LINKED ISSUE #126: Document usage of Overriding Default Distribution Download Url
**Is your feature request related to a problem?**
Logic to Override Default Distribution Download Url with custom Url has been completed in OpenSearch repo. We need to document this change and it's usage. (OpenSearch issue : https://github.com/opensearch-project/OpenSearch/issues/1240)

**What solution would you like?**
Add the usage of overriding default distribution download plugin with custom url in Testing.md file.

**What alternatives have you considered?**

**Do you have any additional context?**

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-off-by: Rishikesh1159 <rishireddy1159@gmail.com>

### Description
This PR will allow developers to override Default Distribution Download URL with custom URL by setting "customDistributionUrl". This will help to pull artifacts from custom location for testing during release process.
 
### Issues Resolved
#126 
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by saratvemulapalli — APPROVED** [review]

**Comment by dblock** [comment]
We rolled this back, right? Let us know when this can be merged @Rishikesh1159.

**Comment by Rishikesh1159** [comment]
Yes we rolled this back. Sure @dblock I will let you know once I open a PR and get it merged in OpenSearch repo, then we can merge this.

**Comment by Rishikesh1159** [comment]
> @Rishikesh1159 we merged the changes to 2.0. Is this ready for review

@saratvemulapalli small change was needed from last commit. Made it now, it is ready for review.

**Comment by dblock** [comment]
@Rishikesh1159 should I merge this? I remember something about this change being reverted ...

**Comment by Rishikesh1159** [comment]
Yes @dblock please merge it. After reverting it was fixed and merged changes with this PR :https://github.com/opensearch-project/OpenSearch/pull/2420

**Review by saratvemulapalli — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Pull request merged**
